# LiveKit configuration
[plugins]
  
# STT model 
[plugins.stt]
provider = "faster_whisper"
path = "src/plugins/stt_faster_whisper.py"




# Text-to-Speech (TTS)
[plugins.tts]
provider = "piper"
path = "src/plugins/tts_piper.py"
